name: Push Dummy Commit to Commons Repo

# Workflow is triggered manually
on:
  workflow_dispatch:

permissions:
  contents: write  # Still keep this to ensure write permissions

jobs:
  push_commons_changes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the arena repository
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: "dev"  # Checkout the 'dev' branch of your main repo
          fetch-depth: 0  # Fetch full history to make git subtree work

      # Step 2: Set up Git identity (before commit)
      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Create a dummy commit in the commons folder
      - name: Create Dummy Commit in Commons Folder
        run: |
          # Create a test file in the commons folder
          echo "This is a dummy commit to verify subtree push" > commons/dummy-file.txt
          git add commons/dummy-file.txt
          git commit -m "chore: Add dummy commit to commons folder"

      # Step 4: Push the changes in the commons folder to the commons repository using subtree
      - name: Push to Commons Repo using Subtree
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --unset-all http.github.com/.extraheader
          COMMONS_REPO_URL="https://${{ secrets.PAT_TOKEN }}@github.com/anagarwa/first-helix-website.git"
          BRANCH_NAME="commons-push-$(date +'%Y%m%d%H%M')"

          # Push only the contents of the 'commons' folder to the commons repo
          git remote add commons $COMMONS_REPO_URL
          git subtree push --prefix=commons commons $BRANCH_NAME
