name: Prevent Mixed Changes on PR

on:
  pull_request:
    branches:
      - dev

jobs:
  check-commons-folder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for mixed changes in commits
        run: |
          # Get all the commits in the PR
          commits=$(git log --pretty=format:"%H" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          
          # Initialize flags for detecting mixed changes
          commons_changes_in_commit=false
          non_commons_changes_in_commit=false
          
          # Loop through each commit to check for mixed changes
          for commit in $commits; do
            # Get the list of files changed in the current commit
            files=$(git diff-tree --no-commit-id --name-only -r $commit)
          
            commons_changes=$(echo "$files" | grep '^commons/' || true)
            other_changes=$(echo "$files" | grep -v '^commons/' || true)
          
            if [ -n "$commons_changes" ] && [ -n "$other_changes" ]; then
              echo "Error: Commit $commit contains changes in both 'commons/' and other folders."
              exit 1
            fi
          done