name: Prevent Mixed Changes on PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - dev

jobs:
  check-commons-folder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all commit history so we can compare across commits

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Check for changes in 'commons/' folder
        run: |
          # Get all the commits in the PR
          commits=$(git log --pretty=format:"%H" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          
          commons_changes_detected=false
          for commit in $commits; do
            files=$(git diff-tree --no-commit-id --name-only -r $commit)
            commons_changes=$(echo "$files" | grep '^commons/' || true)
            if [ -n "$commons_changes" ]; then
              commons_changes_detected=true
              break
            fi
          done

          if [ "$commons_changes_detected" = true ]; then
            pr_body="${{ github.event.pull_request.body }}"
            commons_pr_url=$(echo "$pr_body" | grep -oE 'https://github\.com/anagarwa/first-helix-website/pull/[0-9]+')

            if [ -n "$commons_pr_url" ]; then
              echo "Commons repo PR link found: $commons_pr_url"
              commons_pr_number=$(echo "$commons_pr_url" | grep -oE '[0-9]+$')

              # Clone the commons repo using SSH
              git clone git@github.com:anagarwa/first-helix-website.git commons-repo
              cd commons-repo

              # Fetch the specific pull request branch
              git fetch origin pull/$commons_pr_number/head:commons-pr-branch
              git checkout commons-pr-branch

              # Get the diff from the commons PR
              commons_repo_diff=$(git diff --name-only origin/main commons-pr-branch | grep '^commons/' || true)
              cd ..

              # Get the diff in the current PR for commons folder
              current_pr_diff=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^commons/' || true)

              # Compare the diffs
              if [ "$commons_repo_diff" = "$current_pr_diff" ]; then
                echo "Changes in commons repo PR match the changes in the commons/ folder."
              else
                echo "Error: Changes in commons repo PR do not match the changes in the commons/ folder of this PR."
                exit 1
              fi
            else
              echo "Error: Changes in 'commons/' folder detected, but no link to commons repo PR found."
              exit 1
            fi
          fi
