name: Push to Commons Repo

on:
  workflow_dispatch:

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up SSH key
        uses: actions/setup-ssh@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-private-key-file: ~/.ssh/id_rsa

      - name: Add remote repository
        run: git remote add upstream git@github.com:anagarwa/first-helix-website.git

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Create dummy commit in commons folder
        run: |
          cd commons
          touch dummy_file.txt
          git add dummy_file.txt
          git commit -m "Dummy commit"
          cd ..

      - name: Push subtree changes to upstream
        run: git subtree push --prefix commons upstream dev